# -*- coding: utf-8 -*-
"""Weekly position-delta digest: for every project with a living position,
compare the position now vs a week ago (plus interim events), AI-write one
what-moved email, and send it to active admins. Runs Monday morning."""
import datetime as dt
import json
import logging
import os

import tk_ai
import tk_db
import tk_email

LOG = logging.getLogger("tk_digest")

DIGEST_SCHEMA = {
    "type": "object",
    "properties": {
        "digest_html": {
            "type": "string",
            "description": "the digest as an HTML fragment (no doctype/html/body)",
        },
        "headline": {"type": "string", "description": "one-line summary for the subject"},
    },
    "required": ["digest_html", "headline"],
}

DIGEST_SYSTEM = (
    "You write the Monday position-delta digest for Yo-Chi's finance TaskHub. For each "
    "project you get the position document as it stood a week ago, the position now, and "
    "any interim events. Write digest_html as an HTML fragment (h3 per project, p/ul/li, "
    "strong; no other tags) covering ONLY what CHANGED in the week: resolved items (with "
    "evidence), new items, items that worsened/escalated, and long-carried items now aging "
    "(quote the [first seen] date). Skip projects with no meaningful movement in one "
    "combined line at the end. Rank projects worst-first. Be quantitative (venues, "
    "suppliers, dollars, dates), under 450 words, factual tone. headline = one sentence, "
    "the single most important change. Fast Food Award items are 'areas to review', never "
    "'breaches'. Money is AUD net of GST."
)


def _baseline(project_id, cutoff_iso):
    rows = tk_db.get("positions", {
        "project_id": "eq." + project_id,
        "created_at": "lte." + cutoff_iso,
        "order": "version.desc", "limit": "1", "select": "version,content,created_at"})
    return rows[0] if rows else None


def run():
    cutoff = (dt.datetime.utcnow() - dt.timedelta(days=7)).isoformat() + "Z"
    projects = {p["id"]: p["name"] for p in tk_db.get("projects", {"select": "id,name"})}
    latest_by_project = {}
    for row in tk_db.get("positions", {"order": "project_id,version.desc",
                                       "select": "project_id,version,content,events,created_at"}):
        latest_by_project.setdefault(row["project_id"], row)

    deltas, unchanged = [], []
    for pid, cur in latest_by_project.items():
        name = projects.get(pid, "(unknown project)")
        base = _baseline(pid, cutoff)
        moved = (cur["created_at"] > cutoff) or (cur.get("events") or [])
        if base and base["version"] == cur["version"] and not (cur.get("events") or []):
            unchanged.append(name)
            continue
        deltas.append({
            "project": name,
            "position_week_ago": (base or {}).get("content", "(no position a week ago - new)"),
            "position_now": cur["content"],
            "interim_events": [e.get("text", "") for e in (cur.get("events") or [])],
            "moved": bool(moved),
        })
    if not deltas:
        return {"projects": 0, "sent": 0, "note": "no positions moved this week"}

    out = tk_ai.structured(
        DIGEST_SYSTEM,
        "Week ending %s.\n\nProjects:\n%s%s" % (
            dt.date.today().isoformat(),
            json.dumps(deltas, separators=(",", ":"))[:60000],
            ("\n\nProjects with no movement (mention in one line): " + ", ".join(unchanged))
            if unchanged else ""),
        "write_digest", DIGEST_SCHEMA, max_tokens=3000)

    app_url = os.environ.get("APP_URL", "")
    html = ("<div style='font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;"
            "font-size:13.5px;color:#1f2937;line-height:1.55'>"
            "<p><b>Weekly position digest</b> — what moved across project positions in the "
            "last 7 days.</p>%s"
            "<p><a href='%s' style='display:inline-block;background:#23824a;color:#fff;"
            "text-decoration:none;font-weight:700;font-size:13px;padding:8px 16px;"
            "border-radius:8px'>Open TaskHub &rarr;</a></p>"
            "<p style='color:#6b7280;font-size:11.5px'>Generated by the TaskHub weekly "
            "digest from the 📍 Position documents.</p></div>") % (out["digest_html"], app_url)
    admins = tk_db.get("profiles", {"role": "eq.admin", "active": "eq.true",
                                    "select": "email"})
    sent = 0
    for a in admins:
        if tk_email.send(a["email"], "Position digest — %s" % out["headline"][:120], html):
            sent += 1
    return {"projects": len(deltas), "unchanged": len(unchanged), "sent": sent}
