# -*- coding: utf-8 -*-
"""Task routines: a saved, runnable analysis on a task.

The flow Peter asked for, end to end:

  ASK      on the task, describe what the routine should do in plain English
           ("check Xero across all entities for overdue invoices")
  PROPOSE  the builder reads the ask plus the task's own context, scans the
           lake schema, writes the brief and the data queries, and VALIDATES
           every query against the live lake before showing anything
  SAVE     the proposal becomes a row in ai_skills tied to this task - with
           the recipients and formats (pdf/xlsx/csv, any mix) the user chose
  RUN      a button (or the daily schedule): fresh data, an AI-written review,
           rendered to every requested format, emailed to every recipient,
           and posted to the task as a comment
  REFINE   plain-English feedback rewrites the brief/queries, re-validates,
           bumps the version and keeps the old ask in the refinement trail
  LEARN    every run is recorded into the task playbook, so the Approach tab
           accumulates what worked - the routine gets sharper with use

Runs are synchronous (queries are capped and validated, the whole path fits
the HTTP window); scheduled runs ride the existing skills timer."""
import datetime as dt
import json
import logging
import re

import tk_ai
import tk_db
import tk_email
import tk_render
import lake_reader

LOG = logging.getLogger("tk_taskskill")

REVIEW_SYSTEM = (
    "You are the finance analyst for Yo-Chi (Australian frozen-yoghurt group). "
    "You are executing a saved routine. You get its brief and fresh data pulls "
    "(JSON; money is AUD net of GST unless stated). Write the result as PLAIN "
    "TEXT: one line up front - Good / Watch / Action needed - with the single "
    "number that matters, then short titled sections per the brief with "
    "specific entities and amounts, then 'Recommendations:' with 2-4 concrete "
    "next steps. Only use the data given; if a pull errored or is empty, say "
    "so plainly rather than working around it. Never call Fast Food Award "
    "items 'breaches' - say 'areas to review'. Under ~400 words."
)

EMAIL_NOTE = ("Generated by the '%s' routine on Yo-Chi TaskHub. Reply-all is "
              "human territory - this address only sends.")


def _emails(raw):
    """Recipients as a clean list; garbage is reported, not silently dropped."""
    good, bad = [], []
    for part in re.split(r"[,;\s]+", raw or ""):
        if not part:
            continue
        if re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", part):
            good.append(part.lower())
        else:
            bad.append(part)
    return good, bad


def _task(task_id):
    rows = tk_db.get("tasks", {"id": "eq." + task_id,
                               "select": "id,title,description,project_id,assignee_id"})
    if not rows:
        raise ValueError("task not found")
    return rows[0]


def get(task_id):
    rows = tk_db.get("ai_skills", {
        "task_id": "eq." + task_id, "select":
        "id,task_id,name,prompt,data_queries,cadence,weekday,recipients,formats,ask,"
        "active,version,refinements,last_run_at,last_result",
        "order": "created_at.desc", "limit": "1"})
    return rows[0] if rows else None


def propose(task_id, ask, recipients="", formats="pdf", cadence="on-demand"):
    """Build and validate the routine, but save nothing - the person sees the
    plan before anything exists."""
    import tk_skillbuilder
    task = _task(task_id)
    good, bad = _emails(recipients)
    description = (
        "%s\n\nContext - this routine belongs to the TaskHub task '%s'"
        "%s. Cadence wanted: %s." % (
            ask, task["title"],
            (": %s" % task["description"][:400]) if task.get("description") else "",
            cadence))
    draft = tk_skillbuilder.build(description)
    return {
        "task_id": task_id, "ask": ask,
        "name": draft.get("name") or task["title"][:80],
        "prompt": draft.get("prompt"),
        "data_queries": draft.get("data_queries"),
        "validation": draft.get("validation"),
        "cadence": cadence if cadence in ("on-demand", "daily", "weekly", "monthly")
                   else "on-demand",
        "weekday": draft.get("weekday"),
        "recipients": ", ".join(good), "invalid_recipients": bad,
        "formats": formats,
    }


def save(task_id, proposal, uid=None):
    """The reviewed proposal becomes the saved routine (one per task - saving
    again replaces it, with the old version kept in the refinement trail)."""
    task = _task(task_id)
    existing = get(task_id)
    good, bad = _emails(proposal.get("recipients"))
    if bad:
        raise ValueError("these are not email addresses: %s" % ", ".join(bad[:5]))
    row = {
        "task_id": task_id,
        "name": (proposal.get("name") or task["title"])[:120],
        "ask": proposal.get("ask") or "",
        "prompt": proposal.get("prompt") or "",
        "data_queries": proposal.get("data_queries") or [],
        "cadence": proposal.get("cadence") or "on-demand",
        "weekday": proposal.get("weekday"),
        "project_id": task["project_id"],
        "assignee_id": task.get("assignee_id"),
        "recipients": ", ".join(good),
        "formats": proposal.get("formats") or "pdf",
        "email_review": bool(good),
        "active": True,
        "updated_at": dt.datetime.utcnow().isoformat() + "Z",
    }
    if existing:
        trail = existing.get("refinements") or []
        trail.append({"at": row["updated_at"], "by": uid,
                      "kind": "re-saved", "previous_ask": existing.get("ask"),
                      "previous_version": existing.get("version")})
        row["refinements"] = trail
        row["version"] = int(existing.get("version") or 1) + 1
        tk_db.patch("ai_skills", {"id": "eq." + existing["id"]}, row)
        row["id"] = existing["id"]
    else:
        out = tk_db.insert("ai_skills", [row], returning=True)
        row["id"] = out[0]["id"]
    return {"saved": True, "id": row["id"], "version": row.get("version", 1)}


def execute(skill, actor=None, email=True):
    """One run: fresh data -> review -> render -> email -> comment -> learn."""
    started = dt.datetime.utcnow()
    pulls = {}
    for q in (skill.get("data_queries") or []):
        label = q.get("label", "data")
        try:
            lake_reader.sync(extra_tables=lake_reader.referenced_tables(q["sql"]),
                             log=LOG.info)
            pulls[label] = lake_reader.query(q["sql"], max_rows=200)
        except Exception as e:
            pulls[label] = {"error": str(e)[:200]}

    review = tk_ai.text(
        REVIEW_SYSTEM,
        "Routine: %s\nToday: %s\n\nBrief:\n%s\n\nData pulls:\n%s" % (
            skill["name"], dt.date.today().isoformat(), skill["prompt"],
            json.dumps(pulls, separators=(",", ":"), default=str)[:60000]),
        max_tokens=1600)

    attachments, render_problems = tk_render.render(
        skill.get("formats") or "pdf", skill["name"], review, pulls)

    recipients, _ = _emails(skill.get("recipients"))
    sent_to, email_errors = [], []
    if email and recipients and attachments is not None:
        html = ("<div style='font-family:-apple-system,Segoe UI,Arial,sans-serif;"
                "max-width:760px;color:#222'><pre style='font-family:inherit;"
                "white-space:pre-wrap;font-size:13px'>%s</pre>"
                "<p style='color:#888;font-size:11px'>%s</p></div>" % (
                    review.replace("&", "&amp;").replace("<", "&lt;"),
                    EMAIL_NOTE % skill["name"]))
        for addr in recipients:
            try:
                if tk_email.send(addr, "%s — %s" % (skill["name"],
                                                    dt.date.today().strftime("%d %b %Y")),
                                 html, attachments=attachments):
                    sent_to.append(addr)
            except Exception as e:
                LOG.exception("routine email to %s failed", addr)
                email_errors.append("%s: %s" % (addr, str(e)[:100]))

    # the run lands on the task, whatever happened to the email
    summary = {
        "ran_at": started.isoformat() + "Z",
        "secs": round((dt.datetime.utcnow() - started).total_seconds()),
        "pulls": {k: ("error" if v.get("error") else len(v.get("rows") or []))
                  for k, v in pulls.items()},
        "formats": [a["name"] for a in attachments],
        "sent_to": sent_to, "email_errors": email_errors,
        "render_problems": render_problems,
        "headline": (review or "").splitlines()[0][:200] if review else "",
    }
    if skill.get("task_id"):
        try:
            tk_db.insert("comments", [{
                "task_id": skill["task_id"], "author_id": actor,
                "body": "▶ Routine run — %s\n\n%s%s%s" % (
                    skill["name"], review,
                    ("\n\nSent to: %s" % ", ".join(sent_to)) if sent_to else
                    "\n\n(no email sent%s)" % (
                        " - no recipients saved" if not recipients else ""),
                    ("\nProblems: %s" % "; ".join(render_problems + email_errors))
                    if (render_problems or email_errors) else "")}])
        except Exception:
            LOG.exception("could not post the run to the task")
        try:
            import tk_playbook
            task = _task(skill["task_id"])
            tk_playbook.record(
                task["title"], None,
                {"approach": skill.get("prompt"),
                 "data_queries": skill.get("data_queries"),
                 "ask": skill.get("ask")},
                summary=summary["headline"],
                outcome="success" if not pulls_failed(pulls) else "partial")
        except Exception:
            LOG.exception("playbook learning failed (run itself succeeded)")

    tk_db.patch("ai_skills", {"id": "eq." + skill["id"]},
                {"last_run_at": started.isoformat() + "Z",
                 "last_result": summary})
    return dict(summary, review=review)


def pulls_failed(pulls):
    return any(v.get("error") for v in (pulls or {}).values())


def run_now(task_id, actor=None, email=True):
    skill = get(task_id)
    if not skill:
        raise ValueError("no routine saved on this task yet")
    return execute(skill, actor=actor, email=email)


REFINE_SYSTEM = (
    "You maintain a saved finance data routine (brief + DuckDB queries). The "
    "user gives feedback on how it should change. Return the FULL updated "
    "routine - whole brief, all queries - not a diff. Keep everything that "
    "still holds; change only what the feedback asks. The same STRICT SQL "
    "rules apply: SELECT/WITH only, bare view names, CAST(col AS DATE) before "
    "date maths, aggregate to a useful grain, ORDER BY the interesting metric, "
    "under ~200 rows."
)


def refine(task_id, feedback, uid=None):
    """Plain-English feedback -> updated brief and queries, re-validated, with
    the previous version kept in the trail. This is how the routine learns
    from its owner rather than only from its runs."""
    import tk_skillbuilder
    skill = get(task_id)
    if not skill:
        raise ValueError("no routine saved on this task yet")
    draft = tk_ai.structured(
        REFINE_SYSTEM,
        "CURRENT ROUTINE\nName: %s\nBrief:\n%s\n\nQueries:\n%s\n\nLAST RUN "
        "RESULT (context): %s\n\nLAKE SCHEMA:\n%s\n\nFEEDBACK:\n%s" % (
            skill["name"], skill["prompt"],
            json.dumps(skill.get("data_queries"), indent=1),
            json.dumps(skill.get("last_result") or {}, default=str)[:2000],
            tk_skillbuilder._schema_text(),
            feedback),
        "refine_routine", tk_skillbuilder.TOOL_SCHEMA, max_tokens=3000)
    validation = tk_skillbuilder._validate(draft.get("data_queries") or [])
    if any(not v["ok"] for v in validation):
        # one repair round, mirroring the builder's own
        draft = tk_ai.structured(
            tk_skillbuilder.REPAIR_SYSTEM,
            "Lake schema:\n%s\n\nRoutine brief:\n%s\n\nYour queries:\n%s\n\n"
            "Validation results:\n%s\n\nReturn the full corrected skill." % (
                tk_skillbuilder._schema_text(), draft.get("prompt") or "",
                json.dumps(draft.get("data_queries"), separators=(",", ":")),
                json.dumps(validation, separators=(",", ":"))),
            "build_skill", tk_skillbuilder.TOOL_SCHEMA, max_tokens=3000)
        validation = tk_skillbuilder._validate(draft.get("data_queries") or [])
        if any(not v["ok"] for v in validation):
            bad = [v for v in validation if not v["ok"]]
            raise ValueError("the refined queries do not validate: %s"
                             % "; ".join(v.get("error", "?")[:80] for v in bad[:3]))
    trail = skill.get("refinements") or []
    trail.append({"at": dt.datetime.utcnow().isoformat() + "Z", "by": uid,
                  "kind": "refined", "feedback": feedback[:500],
                  "previous_version": skill.get("version")})
    tk_db.patch("ai_skills", {"id": "eq." + skill["id"]}, {
        "name": (draft.get("name") or skill["name"])[:120],
        "prompt": draft.get("prompt") or skill["prompt"],
        "data_queries": draft.get("data_queries") or skill["data_queries"],
        "refinements": trail,
        "version": int(skill.get("version") or 1) + 1,
        "updated_at": dt.datetime.utcnow().isoformat() + "Z"})
    return {"refined": True, "version": int(skill.get("version") or 1) + 1,
            "name": draft.get("name"), "prompt": draft.get("prompt"),
            "data_queries": draft.get("data_queries")}
